

// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Local
namespace Performance.Contratcs
{
    using System;
    using System.Runtime.Serialization;

    using Voogd.Library.Messaging;

    #region Generated by Lokad Code DSL
  [DataContract(Namespace = "Contracts")]
  public partial class PerformanceMessage
  {
    [DataMember(Order = 1)] public string Description { get; private set; }
    [DataMember(Order = 2)] public DateTime SendAt { get; private set; }
    
    PerformanceMessage () {}
    public PerformanceMessage (string description, DateTime sendAt)
    {
      this.Description = description;
      this.SendAt = sendAt;
    }
  }
  [DataContract(Namespace = "Contracts")]
  public partial class ProcessPerformanceMessage : Command, ICommand
  {
    [DataMember(Order = 1)] public Guid AggregateId { get; private set; }
    [DataMember(Order = 2)] public PerformanceMessage PerformanceMessage { get; private set; }
    
    ProcessPerformanceMessage () {}
    public ProcessPerformanceMessage (Guid aggregateId, PerformanceMessage performanceMessage)
    {
      this.AggregateId = aggregateId;
      this.PerformanceMessage = performanceMessage;
    }
  }
  [DataContract(Namespace = "Contracts")]
  public partial class PerformanceMessageProcessed : Event, IEvent
  {
    [DataMember(Order = 1)] public Guid AggregateId { get; private set; }
    [DataMember(Order = 2)] public DateTime ProcessedAt { get; private set; }
    
    PerformanceMessageProcessed () {}
    public PerformanceMessageProcessed (Guid aggregateId, DateTime processedAt)
    {
      this.AggregateId = aggregateId;
      this.ProcessedAt = processedAt;
    }
  }
  
  public interface IPerformanceTesterApplicationService
  {
    void When(ProcessPerformanceMessage c);
  }
  
  public interface IPerformanceTesterState
  {
    void When(PerformanceMessageProcessed e);
  }
  #endregion
}
